###############################################################################
# analysis.R
#
# Post-simulation analysis and visualization.
# Loads results from CSVs generated by run_simulations.R and produces
# plots and summary statistics.
#
# Run from the project root:
#   Rscript simulations/analysis.R
###############################################################################

library(ggplot2)
library(reshape2)
library(dplyr)
library(scales)

results_dir <- "simulations/results"

# ─────────────────────────────────────────────────────────────────────────────
# EXPERIMENT 1: c_star Magnitude Scaling
# ─────────────────────────────────────────────────────────────────────────────
cat("=== Analyzing Experiment 1: c_star Magnitude ===\n")

exp1 <- read.csv(file.path(results_dir, "exp1_cstar_magnitude.csv"))

# Plot: Loss reduction by PCA vs DIIM as c_star scales
exp1_long <- melt(exp1[, c("multiplier", "reduction_diim", "reduction_pca")],
                  id.vars = "multiplier",
                  variable.name = "method",
                  value.name = "loss_reduction")

p1 <- ggplot(exp1_long, aes(x = multiplier, y = loss_reduction, color = method)) +
  geom_line(size = 1.2) +
  geom_point(size = 2.5) +
  geom_vline(xintercept = exp1$multiplier[which(exp1$pca_wins != lag(exp1$pca_wins))],
             linetype = "dashed", color = "gray40", alpha = 0.7) +
  scale_color_manual(
    values = c("reduction_diim" = "#3498DB", "reduction_pca" = "#2ECC71"),
    labels = c("DIIM Sectors", "PCA Sectors")
  ) +
  labs(
    title = "Experiment 1: Loss Reduction vs c* Magnitude",
    subtitle = "Which method reduces economic loss more as external shock (c*) scales?",
    x = "c* Multiplier (0 = no shock, 1 = original, 2 = doubled)",
    y = "Economic Loss Reduction",
    color = "Method"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    legend.position = "bottom"
  )

ggsave(file.path(results_dir, "exp1_loss_reduction.png"), p1, width = 10, height = 6)
cat("  -> Saved exp1_loss_reduction.png\n")

# Plot: Difference (PCA reduction - DIIM reduction)
exp1$advantage_pca <- exp1$reduction_pca - exp1$reduction_diim

p1b <- ggplot(exp1, aes(x = multiplier, y = advantage_pca)) +
  geom_line(size = 1.2, color = "#8E44AD") +
  geom_point(size = 2.5, color = "#8E44AD") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", size = 0.8) +
  annotate("rect", xmin = min(exp1$multiplier), xmax = max(exp1$multiplier),
           ymin = 0, ymax = Inf, fill = "#2ECC71", alpha = 0.1) +
  annotate("rect", xmin = min(exp1$multiplier), xmax = max(exp1$multiplier),
           ymin = -Inf, ymax = 0, fill = "#E74C3C", alpha = 0.1) +
  annotate("text", x = max(exp1$multiplier) * 0.85, y = max(exp1$advantage_pca) * 0.8,
           label = "PCA Better", color = "#27AE60", fontface = "bold", size = 4) +
  annotate("text", x = max(exp1$multiplier) * 0.85, y = min(exp1$advantage_pca) * 0.8,
           label = "DIIM Better", color = "#C0392B", fontface = "bold", size = 4) +
  labs(
    title = "Experiment 1: PCA Advantage over DIIM",
    subtitle = "Positive values = PCA reduces more loss; Negative = DIIM reduces more",
    x = "c* Multiplier",
    y = "PCA - DIIM Loss Reduction (Advantage)"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold", size = 14))

ggsave(file.path(results_dir, "exp1_pca_advantage.png"), p1b, width = 10, height = 6)
cat("  -> Saved exp1_pca_advantage.png\n")

# Also show the DIIM sectors changing
cat("\n  DIIM key sectors at each c* multiplier:\n")
for (i in 1:nrow(exp1)) {
  cat(sprintf("    c*=%.1f: DIIM sectors=[%s], overlap=%d, PCA wins=%s\n",
              exp1$multiplier[i], exp1$diim_sectors[i],
              exp1$overlap[i], exp1$pca_wins[i]))
}


# ─────────────────────────────────────────────────────────────────────────────
# EXPERIMENT 2: c_star Concentration vs Spread
# ─────────────────────────────────────────────────────────────────────────────
cat("\n=== Analyzing Experiment 2: c_star Distribution ===\n")

exp2 <- read.csv(file.path(results_dir, "exp2_cstar_distribution.csv"))

# Bar chart comparing loss reduction
exp2_long <- melt(exp2[, c("pattern", "reduction_diim", "reduction_pca", "c_star_gini")],
                  id.vars = c("pattern", "c_star_gini"),
                  variable.name = "method",
                  value.name = "loss_reduction")

# Order by Gini coefficient
exp2_long$pattern <- reorder(exp2_long$pattern, exp2_long$c_star_gini)

p2 <- ggplot(exp2_long, aes(x = pattern, y = loss_reduction, fill = method)) +
  geom_bar(stat = "identity", position = "dodge", alpha = 0.85) +
  scale_fill_manual(
    values = c("reduction_diim" = "#3498DB", "reduction_pca" = "#2ECC71"),
    labels = c("DIIM Sectors", "PCA Sectors")
  ) +
  labs(
    title = "Experiment 2: Loss Reduction by c* Distribution Pattern",
    subtitle = "Ordered by Gini coefficient (left = uniform, right = concentrated)",
    x = "c* Distribution Pattern",
    y = "Economic Loss Reduction",
    fill = "Method"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom"
  )

ggsave(file.path(results_dir, "exp2_distribution_comparison.png"), p2, width = 10, height = 6)
cat("  -> Saved exp2_distribution_comparison.png\n")

cat("\n  Summary:\n")
for (i in 1:nrow(exp2)) {
  cat(sprintf("    Pattern: %-20s Gini=%.3f  DIIM reduction=%.2f  PCA reduction=%.2f  PCA wins=%s\n",
              exp2$pattern[i], exp2$c_star_gini[i],
              exp2$reduction_diim[i], exp2$reduction_pca[i], exp2$pca_wins[i]))
}


# ─────────────────────────────────────────────────────────────────────────────
# EXPERIMENT 3: q0 Uniformity
# ─────────────────────────────────────────────────────────────────────────────
cat("\n=== Analyzing Experiment 3: q0 Uniformity ===\n")

exp3 <- read.csv(file.path(results_dir, "exp3_q0_uniformity.csv"))

exp3$advantage_pca <- exp3$reduction_pca - exp3$reduction_diim

p3 <- ggplot(exp3, aes(x = factor(c_star_multiplier), y = advantage_pca,
                        fill = q0_pattern)) +
  geom_bar(stat = "identity", position = "dodge", alpha = 0.85) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  scale_fill_brewer(palette = "Set2", name = "q0 Pattern") +
  labs(
    title = "Experiment 3: PCA Advantage by q0 Pattern and c* Level",
    subtitle = "Positive = PCA better, Negative = DIIM better",
    x = "c* Multiplier",
    y = "PCA - DIIM Loss Reduction"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    legend.position = "bottom"
  )

ggsave(file.path(results_dir, "exp3_q0_uniformity.png"), p3, width = 10, height = 6)
cat("  -> Saved exp3_q0_uniformity.png\n")


# ─────────────────────────────────────────────────────────────────────────────
# EXPERIMENT 4: Lockdown × c_star Heatmap
# ─────────────────────────────────────────────────────────────────────────────
cat("\n=== Analyzing Experiment 4: Lockdown x c_star Grid ===\n")

exp4 <- read.csv(file.path(results_dir, "exp4_lockdown_cstar_grid.csv"))

exp4$advantage_pca <- exp4$reduction_pca - exp4$reduction_diim

# Heatmap: PCA advantage
p4 <- ggplot(exp4, aes(x = factor(c_star_multiplier),
                        y = factor(lockdown_duration),
                        fill = advantage_pca)) +
  geom_tile(color = "white", size = 0.3) +
  scale_fill_gradient2(
    low = "#E74C3C", mid = "white", high = "#2ECC71", midpoint = 0,
    name = "PCA\nAdvantage"
  ) +
  labs(
    title = "Experiment 4: PCA Advantage Heatmap",
    subtitle = "Green = PCA better, Red = DIIM better",
    x = "c* Multiplier",
    y = "Lockdown Duration (days)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

ggsave(file.path(results_dir, "exp4_heatmap.png"), p4, width = 10, height = 8)
cat("  -> Saved exp4_heatmap.png\n")

# Binary heatmap: PCA wins (TRUE/FALSE)
p4b <- ggplot(exp4, aes(x = factor(c_star_multiplier),
                         y = factor(lockdown_duration),
                         fill = pca_wins)) +
  geom_tile(color = "white", size = 0.3) +
  scale_fill_manual(
    values = c("TRUE" = "#2ECC71", "FALSE" = "#E74C3C"),
    labels = c("TRUE" = "PCA Wins", "FALSE" = "DIIM Wins"),
    name = "Winner"
  ) +
  labs(
    title = "Experiment 4: Which Method Wins?",
    subtitle = "Binary outcome across lockdown duration and c* multiplier",
    x = "c* Multiplier",
    y = "Lockdown Duration (days)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

ggsave(file.path(results_dir, "exp4_binary_heatmap.png"), p4b, width = 10, height = 8)
cat("  -> Saved exp4_binary_heatmap.png\n")


# ─────────────────────────────────────────────────────────────────────────────
# EXPERIMENT 5: Monte Carlo Analysis
# ─────────────────────────────────────────────────────────────────────────────
cat("\n=== Analyzing Experiment 5: Monte Carlo ===\n")

exp5 <- read.csv(file.path(results_dir, "exp5_monte_carlo.csv"))

cat(sprintf("  Overall PCA win rate: %.1f%% (%d / %d)\n",
            mean(exp5$pca_wins) * 100, sum(exp5$pca_wins), nrow(exp5)))

# Scatter: c_star_gini vs q0_gini, colored by winner
p5a <- ggplot(exp5, aes(x = c_star_gini, y = q0_gini, color = pca_wins)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_manual(
    values = c("TRUE" = "#2ECC71", "FALSE" = "#E74C3C"),
    labels = c("TRUE" = "PCA Wins", "FALSE" = "DIIM Wins"),
    name = "Winner"
  ) +
  labs(
    title = "Experiment 5: Monte Carlo — Gini Coefficients",
    subtitle = "Each point is one random scenario",
    x = "c* Gini (higher = more concentrated)",
    y = "q0 Gini (higher = more concentrated)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    legend.position = "bottom"
  )

ggsave(file.path(results_dir, "exp5_gini_scatter.png"), p5a, width = 10, height = 7)
cat("  -> Saved exp5_gini_scatter.png\n")

# Scatter: c_star_mean vs q0_mean, colored by winner
p5b <- ggplot(exp5, aes(x = c_star_mean, y = q0_mean, color = pca_wins)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_manual(
    values = c("TRUE" = "#2ECC71", "FALSE" = "#E74C3C"),
    labels = c("TRUE" = "PCA Wins", "FALSE" = "DIIM Wins"),
    name = "Winner"
  ) +
  labs(
    title = "Experiment 5: Monte Carlo — Mean Values",
    x = "Mean c*",
    y = "Mean q0"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    legend.position = "bottom"
  )

ggsave(file.path(results_dir, "exp5_means_scatter.png"), p5b, width = 10, height = 7)
cat("  -> Saved exp5_means_scatter.png\n")

# Feature importance: which variables best predict PCA winning?
# Use logistic regression coefficients
exp5$pca_wins_int <- as.integer(exp5$pca_wins)

logit_model <- glm(pca_wins_int ~ c_star_mean + c_star_sd + c_star_gini +
                     q0_mean + q0_sd + q0_gini +
                     cstar_q0_cor + c_star_pca_share + q0_pca_share +
                     lockdown_duration + overlap,
                   data = exp5, family = binomial)

# Extract coefficients with p-values
coef_df <- data.frame(
  variable = names(coef(logit_model))[-1],
  coefficient = coef(logit_model)[-1],
  p_value = summary(logit_model)$coefficients[-1, 4]
)
coef_df$significant <- coef_df$p_value < 0.05
coef_df <- coef_df[order(abs(coef_df$coefficient), decreasing = TRUE), ]

p5c <- ggplot(coef_df, aes(x = reorder(variable, abs(coefficient)),
                            y = coefficient,
                            fill = significant)) +
  geom_bar(stat = "identity", alpha = 0.85) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_fill_manual(
    values = c("TRUE" = "#2ECC71", "FALSE" = "#BDC3C7"),
    labels = c("TRUE" = "p < 0.05", "FALSE" = "Not significant"),
    name = "Significance"
  ) +
  coord_flip() +
  labs(
    title = "Experiment 5: Logistic Regression Coefficients",
    subtitle = "Which features predict PCA outperforming DIIM?",
    x = "Feature",
    y = "Logistic Regression Coefficient"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    legend.position = "bottom"
  )

ggsave(file.path(results_dir, "exp5_feature_importance.png"), p5c, width = 10, height = 7)
cat("  -> Saved exp5_feature_importance.png\n")

# Boxplots: distributions of key features split by PCA wins
key_features <- c("c_star_gini", "c_star_mean", "q0_gini", "q0_mean",
                   "c_star_pca_share", "q0_pca_share", "overlap")

exp5$winner <- ifelse(exp5$pca_wins, "PCA Wins", "DIIM Wins")
exp5_features <- melt(exp5[, c("winner", key_features)],
                       id.vars = "winner",
                       variable.name = "feature",
                       value.name = "value")

p5d <- ggplot(exp5_features, aes(x = winner, y = value, fill = winner)) +
  geom_boxplot(alpha = 0.7, outlier.alpha = 0.3) +
  facet_wrap(~feature, scales = "free_y", ncol = 4) +
  scale_fill_manual(values = c("PCA Wins" = "#2ECC71", "DIIM Wins" = "#E74C3C")) +
  labs(
    title = "Experiment 5: Feature Distributions by Winner",
    x = "", y = "Value"
  ) +
  guides(fill = "none") +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    strip.text = element_text(face = "bold", size = 9)
  )

ggsave(file.path(results_dir, "exp5_feature_boxplots.png"), p5d, width = 14, height = 7)
cat("  -> Saved exp5_feature_boxplots.png\n")


# ─────────────────────────────────────────────────────────────────────────────
# SUMMARY: Key Findings
# ─────────────────────────────────────────────────────────────────────────────
cat("\n")
cat("══════════════════════════════════════════════════════════════════\n")
cat("  SUMMARY OF KEY FINDINGS\n")
cat("══════════════════════════════════════════════════════════════════\n\n")

# Exp 1 summary
pca_win_range_exp1 <- exp1$multiplier[exp1$pca_wins == TRUE]
if (length(pca_win_range_exp1) > 0) {
  cat(sprintf("Exp 1: PCA wins for c* multipliers: %s\n",
              paste(pca_win_range_exp1, collapse = ", ")))
} else {
  cat("Exp 1: PCA never wins across tested c* multipliers\n")
}

# Exp 2 summary
pca_win_patterns <- exp2$pattern[exp2$pca_wins == TRUE]
cat(sprintf("Exp 2: PCA wins for c* patterns: %s\n",
            if (length(pca_win_patterns) > 0) paste(pca_win_patterns, collapse = ", ") else "none"))

# Exp 4 summary
pca_win_pct_exp4 <- mean(exp4$pca_wins) * 100
cat(sprintf("Exp 4: PCA win rate across grid: %.1f%%\n", pca_win_pct_exp4))

# Exp 5 summary
cat(sprintf("Exp 5: Monte Carlo PCA win rate: %.1f%%\n",
            mean(exp5$pca_wins) * 100))

# Top predictive features
sig_features <- coef_df[coef_df$significant, ]
if (nrow(sig_features) > 0) {
  cat("\nStatistically significant predictors of PCA winning:\n")
  for (i in 1:nrow(sig_features)) {
    direction <- ifelse(sig_features$coefficient[i] > 0, "increases", "decreases")
    cat(sprintf("  - %s: %s PCA win probability (coef=%.4f, p=%.4f)\n",
                sig_features$variable[i], direction,
                sig_features$coefficient[i], sig_features$p_value[i]))
  }
} else {
  cat("\nNo statistically significant predictors found at p<0.05 level.\n")
}

cat("\n══════════════════════════════════════════════════════════════════\n")
cat("  All analysis complete! Plots saved to simulations/results/\n")
cat("══════════════════════════════════════════════════════════════════\n")
